# Generated by Django 3.2.1 on 2021-05-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swms_manager', '0003_auto_20210505_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlmeasure',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
