# Generated by Django 3.2.1 on 2021-05-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swms_manager', '0005_alter_controlmeasure_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlRiskLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HazardRiskLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobtask',
            name='control_risk',
        ),
        migrations.RemoveField(
            model_name='jobtask',
            name='hazard_risk',
        ),
        migrations.AddField(
            model_name='jobtask',
            name='control_risk',
            field=models.ManyToManyField(to='swms_manager.ControlRiskLevel'),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='hazard_risk',
            field=models.ManyToManyField(to='swms_manager.HazardRiskLevel'),
        ),
    ]
