# Generated by Django 3.2.1 on 2021-05-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swms_manager', '0006_auto_20210505_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtask',
            name='name',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
