# Generated by Django 3.2.1 on 2021-05-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swms_manager', '0007_alter_jobtask_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtask',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
