# Generated by Django 3.2.1 on 2021-05-05 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('swms_manager', '0009_swmsgroup_job_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='swms',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='swms',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='swms',
            name='phone_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='swms',
            name='signature',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
