# Generated by Django 3.2.1 on 2021-05-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swms_manager', '0011_auto_20210505_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlmeasure',
            name='name',
            field=models.CharField(max_length=400, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hazard',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='swmsgroup',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
