# Generated by Django 3.2.1 on 2021-05-10 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swms_manager', '0012_auto_20210505_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='site',
        ),
        migrations.AddField(
            model_name='site',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='swms_manager.job'),
        ),
        migrations.AddField(
            model_name='swms',
            name='swms_group',
            field=models.ManyToManyField(to='swms_manager.JobTask'),
        ),
        migrations.RemoveField(
            model_name='jobtask',
            name='control_risk',
        ),
        migrations.AddField(
            model_name='jobtask',
            name='control_risk',
            field=models.CharField(choices=[('1L', '1A'), ('2M', '2M'), ('3H', '3H'), ('4A', '4A')], max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='jobtask',
            name='hazard_risk',
        ),
        migrations.AddField(
            model_name='jobtask',
            name='hazard_risk',
            field=models.CharField(choices=[('1L', '1A'), ('2M', '2M'), ('3H', '3H'), ('4A', '4A')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ControlRiskLevel',
        ),
        migrations.DeleteModel(
            name='HazardRiskLevel',
        ),
    ]
