# Generated by Django 3.2.1 on 2021-05-10 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swms_manager', '0013_auto_20210510_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swms',
            name='job',
        ),
        migrations.RemoveField(
            model_name='swms',
            name='site',
        ),
        migrations.AddField(
            model_name='job',
            name='swms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='swms_manager.swms'),
        ),
        migrations.AlterField(
            model_name='jobtask',
            name='control_risk',
            field=models.CharField(choices=[('1L', '1L'), ('2M', '2M'), ('3H', '3H'), ('4A', '4A')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobtask',
            name='hazard_risk',
            field=models.CharField(choices=[('1L', '1L'), ('2M', '2M'), ('3H', '3H'), ('4A', '4A')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='swms',
            name='swms_group',
            field=models.ManyToManyField(to='swms_manager.SwmsGroup'),
        ),
    ]
