# Generated by Django 3.2.1 on 2021-05-10 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swms_manager', '0014_auto_20210510_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='swms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swms_manager.swms'),
        ),
    ]
