# Generated by Django 3.2.1 on 2021-05-10 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swms_manager', '0015_alter_job_swms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swms_manager.job'),
        ),
    ]
