# Generated by Django 3.2.1 on 2021-05-10 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swms_manager', '0016_alter_site_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='job',
        ),
        migrations.AddField(
            model_name='job',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='swms_manager.site'),
        ),
        migrations.AlterField(
            model_name='job',
            name='swms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='swms_manager.swms'),
        ),
    ]
