# Generated by Django 3.2.1 on 2021-05-10 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swms_manager', '0017_auto_20210510_1654'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
