# Generated by Django 3.2.1 on 2021-05-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swms_manager', '0018_auto_20210510_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='swms',
            name='job_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='swms',
            name='job_type',
            field=models.CharField(choices=[('Minor Works', 'MW'), ('Construction', 'C'), ('Maintenance', 'M')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='swms',
            name='site_contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='swms',
            name='site_email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='swms',
            name='site_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='swms',
            name='site_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
