# Generated by Django 3.2.1 on 2021-05-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swms_manager', '0022_swmsgroup_job_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swms',
            name='swms_group',
            field=models.ManyToManyField(blank=True, to='swms_manager.SwmsGroup'),
        ),
    ]
