# Generated by Django 3.2.1 on 2021-05-24 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swms_manager', '0023_alter_swms_swms_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swms',
            name='swms_group',
        ),
        migrations.AddField(
            model_name='swmsgroup',
            name='swms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swms_manager.swms'),
        ),
    ]
