# Generated by Django 3.2.1 on 2021-05-24 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swms_manager', '0025_auto_20210524_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, null=True)),
                ('hazards', models.CharField(max_length=400, null=True)),
                ('hazard_risk', models.CharField(choices=[('1L', '1L'), ('2M', '2M'), ('3H', '3H'), ('4A', '4A')], max_length=100, null=True)),
                ('control_measures', models.CharField(max_length=400, null=True)),
                ('control_risk', models.CharField(choices=[('1L', '1L'), ('2M', '2M'), ('3H', '3H'), ('4A', '4A')], max_length=100, null=True)),
                ('responsible_person', models.CharField(blank=True, max_length=100, null=True)),
                ('swms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swms_manager.swms')),
            ],
        ),
    ]
