# Generated by Django 3.2.1 on 2021-05-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swms_manager', '0027_alter_swms_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='swms',
            name='efs_manager_email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='swms',
            name='efs_manager_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='swms',
            name='swms_groups',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='swms',
            name='job_type',
            field=models.CharField(choices=[('MW', 'MW'), ('C', 'C'), ('M', 'M'), ('S', 'S')], max_length=100, null=True),
        ),
    ]
